### PR TITLE
Add tracker

### PR DESCRIPTION
**Pull request by alorma**
Added tracker interface.

It will allow to send tracking events to analytics, fabric etc... when error activity is launched and user clicks on restart app.

Tell me if any other events could be added

[Review on Reviewable](https://reviewable.io/reviews/ereza/customactivityoncrash/17)

### CODE REVIEW

**Comment by Rainer-Lang** [comment]
+1

**Comment by alorma** [comment]
Any news on this PR @ereza?

**Comment by alorma** [comment]
Oeeeeeeeee oeeeeee oeeeeee

**Comment by Ereza** [comment]
Merged in 1.5.0.

I have changed a few things however:
* The class is called "EventListener" instead of "Tracker"
* Added another event when the app is closed via error activity button.
* The event listener gets passed as part of the intent since it can be changed during the execution of the app. This means that it must be serialized, and to avoid crashes, the class must not be an anonymous or non-static inner class. If it is, the library throws an exception.

Thanks for the pull request! ;)

**Pull request merged**
