### PR TITLE
Show default error activity is no Class is defined in .init()

### PR DESCRIPTION
**Pull request by alorma**
This should be tested before merge it.

Maybe, it needs a way to handle "restart" the app in the default error view, we can discuss that

[Review on Reviewable](https://reviewable.io/reviews/ereza/customactivityoncrash/3)

### CODE REVIEW

**Comment by Ereza** [comment]
Thanks for the PR. Actually, I'd like to discuss it a bit.

While I can see the usefulness of having a default error activity, this has two implications that I don't personally like:
* This adds a dependency on platform themes, when Android starts using a new design (maybe Android 6?) the library will have to be updated or it will look ugly. If no default activity is provided that responsibility is passed down to the app developer.
* Maybe translations should be provided for the default activity strings. It can be done by the app developer, but I personally hate translating libraries' strings.

Furthermore, I don't actually think that many people will end up using a default error activity. Everyone will want it customized (theme, colors, layout, restart activity as you pointed out...), and I don't think that many people will show the stacktrace (at least not in a prominent place) since it could overwhelm the user.

**Comment by alorma** [comment]
I'm agree with that, most reponsability should be handled by developer.

But the point with DefaultActivity, is to use the library Out of the box, just one line and everything is done.

Colors custmoizatiuon (in case of Lollipop and above) can be discused, because it can be changed just overriding the default color names.

**Comment by Ereza** [comment]
Yes, I agree that's a nice objective and would simplify adding the library to an existing app.

Any thoughts on how we could restart the app in a simple way? Maybe pass the activity class that has to be launched to the init method? Is there any other way?

**Comment by alorma** [comment]
No i guess there are no other methods.

But init() methods should change a bit, with an extra param Class, and an option to not relaunch any activity.

I will do it later today and update the PR

**Comment by Ereza** [comment]
I've already checked out the PR and I'm making some changes to it, if you want you can wait and send another PR after they are committed :P

**Comment by alorma** [comment]
Ok :)

**Comment by alorma** [comment]
You can push directly to this PR?

**Pull request merged**
